const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  employeeId: { type: Number, required: true, unique: true },
  password: { type: String, required: true },
  
  // Array of 128 numbers generated by face-api.js
  faceDescriptor: { type: [Number], default: [] }, 
  
  // Base64 string for profile picture
  profilePicture: { type: String, default: '' },
  
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('User', UserSchema);